homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 0
  longitude: 0
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: UTC
  # Customization file
  customize: !include_dir_merge_named customize

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
discovery:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google_translate

group: !include_dir_merge_named group
switch: !include_dir_merge_list switch
sensor: !include_dir_merge_list sensor
binary_sensor: !include_dir_merge_list binary_sensor
cover: !include_dir_merge_list cover
climate: !include_dir_merge_list climate
fan: !include_dir_merge_list fan
light: !include_dir_merge_list light


automation: !include automations.yaml
script: !include scripts.yaml

mqtt:
  broker: 127.0.0.1
  port: 1883

# google_assistant:
#   project_id: xxx
#   api_key: xxx