version: '2'
services:
  home-assistant:
    #pi zeroW
    image: 'homeassistant/armhf-homeassistant'
    #pi3
    image: 'homeassistant/raspberrypi3-homeassistant'
    #x86
    #image: 'homeassistant/home-assistant'
    container_name: 'hass'
    restart: always
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - ./config:/config 
    
    network_mode: host
