version: "2"
services:
  duckdns:
    #change the image arm64-latest, arm32v7-latest, arm64v8-latest,  depends on the cpu's architecture
    #image: linuxserver/duckdns:arm32v7-latest

    #pi zero
    image: lsioarmhf/duckdns:latest

    
    container_name: duckdns
    environment:
      - SUBDOMAINS=xxxx
      - TOKEN=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    restart: always
    network_mode: host