version: '2'
services:
  nginx-for-hass:
    image: tobi312/rpi-nginx
    container_name: nginx-for-hass
    network_mode: bridge
    restart: always
    environment:
      #change xxxx to the Duckdns domain name
      #change your email to receive LetsEncrypt Notifications
      - VIRTUAL_HOST=ha.xxxx.duckdns.org
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=ha.xxxx.duckdns.org
      - LETSENCRYPT_EMAIL=youremail@gmail.com
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config:/etc/nginx/conf.d
      - /etc/nginx/vhost.d
