version: '2'
services:
  mqtt:
    image: 'pascaldevink/rpi-mosquitto'
    container_name: 'mqtt'
    network_mode: host
    restart: always

  homeon-mqtt:
    image: 'patuan81/homeon-home-assistant:arm'
    container_name: 'homeon-mqtt'
    network_mode: host
    restart: always
    volumes:
      - ../hass/config:/config 
    environment:
      - MQTT_CONNECTION=127.0.0.1:1883
      - MQTT_PASSWORD=
      - MQTT_USERNAME=
      - SHUID=xxxxxxxxxxxxxxx
      - UDP_PASSWORD=xxxxx
      - UDP_CONNECTION_IP=192.168.1.32
      - UDP_CONNECTION_PORT=5667
      - HOME_ASSISTANT_AUTO_GENERATE_CONFIG=true
      - HOME_ASSISTANTE_GENERATE_SCRIPT=false  