version: "2"

services:
  nginx-ssl-proxy:
    restart: always
    image: tobi312/rpi-nginx
    container_name: nginx-ssl 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config:/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./certs:/etc/nginx/certs:ro"
    network_mode: bridge

  nginx-gen:
    #restart: always
    image: rycus86/arm-docker-gen
    container_name: nginx-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    volumes_from:
      - nginx-ssl-proxy
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    network_mode: bridge

  nginx-letsencrypt:
    restart: always
    image: alexanderkrause/rpi-letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    volumes_from:
      - nginx-ssl-proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/etc/nginx/certs:rw"
    environment:
      - NGINX_PROXY_CONTAINER=nginx-ssl
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    network_mode: bridge