version: '2'
services:
  homebridge:
    #pi zero, pi 3
    image: oznu/homebridge:arm32v6

    container_name: homebridge
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./data:/homebridge
    environment:
      - TZ=Asia/Bangkok
      - PGID=1000
      - PUID=1000
      #- PACKAGES=homebridge-config-ui-x
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080